//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEA_ErpProject102MC_Main.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStokGirisAlt
    {
        public int Id { get; set; }
        public Nullable<int> GenelNo { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public string Barkod { get; set; }
        public string UrunKodu { get; set; }
        public string LotSeriNo { get; set; }
        public Nullable<int> Adet { get; set; }
        public string Not { get; set; }
        public Nullable<System.DateTime> UT { get; set; }
        public Nullable<System.DateTime> SKT { get; set; }
        public Nullable<decimal> AlisFiyat { get; set; }
    }
}
