//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEA_ErpProject102MC_Main.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunler
    {
        public int Id { get; set; }
        public string UrunKodu { get; set; }
        public string UrunAdi { get; set; }
        public string UrunAciklama { get; set; }
        public string KutuIcerik { get; set; }
        public string TedarikciFirmaId { get; set; }
        public string Barkod { get; set; }
        public string Fiyat { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<System.DateTime> UretimTarihi { get; set; }
        public Nullable<System.DateTime> SonKullanmaT { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
